name: Mystick
main: mysticmc.mystick.Main
version: 1.0
api-version: 1.21
author: MysticMC
description: Plugin com comandos e permissões.

commands:
  fly:
    description: Ativa ou desativa o modo de voo.
    usage: /fly [jogador]
  vanish:
    description: Ativa ou desativa o modo vanish.
    usage: /vanish [player/list]
  v:
    description: Ativa ou desativa o modo vanish.
    usage: /vanish [player/list]
  ci:
    description: Limpa o inventário do jogador.
    usage: /ci [jogador]
  everyone:
    description: Envia um aviso Importante.
    usage: /everyone <mensagem>
  heal:
    description: Restaura a vida de um jogador.
    usage: /heal [jogador]
  feed:
    description: Restaura a fome de um jogador.
    usage: /feed [jogador]

permissions:
  mystick.fly:
    description: Permite ativar/desativar o fly para si mesmo.
    default: op
  mystick.heal:
    description: Permite curar a si mesmo.
    default: op
  mystick.feed:
    description: Permite alimentar a si mesmo.
    default: op
  mystick.vanish:
    description: Permite ativar/desativar o vanish para si mesmo.
    default: op
  mystick.ci.me:
    description: Permite limpar o inventário de si mesmo.
    default: op
  mystick.ci.all:
    description: Permite limpar o inventário de outros jogadores.
    default: op
  mystick.everyone:
    description: Permite o jogandor enviar um aviso importante.
    default: op
  mystick.*:
    description: Permite ver jogadores no vanish, ativar/desativar o fly e limpar inventário de qualquer jogador.
    default: op
